# Generated by Django 5.0 on 2023-12-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_rename_last_name_author_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='nick_name',
            new_name='last_name',
        ),
    ]
